name: Autograding Tests
on:
  - workflow_dispatch
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    # ----------------------------
    # Player Test
    - name: Player Test
      id: player
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Player Test
        command: ./gradlew test --tests PlayerTest
        max-score: 1

    # ----------------------------
    # Vlogger Test
    - name: Vlogger Test
      id: vlogger
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Vlogger Test
        command: ./gradlew test --tests VloggerTest
        max-score: 1

    # ----------------------------
    # Painting Test
    - name: Painting Test
      id: painting
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Painting Test
        command: ./gradlew test --tests PaintingTest
        max-score: 1

    # ----------------------------
    # UserApp Test
    - name: UserApp Test
      id: userapp
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: UserApp Test
        command: ./gradlew test --tests UserAppTest
        max-score: 1

    # ----------------------------
    # Autograding Reporter
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PLAYER_RESULTS: "${{steps.player.outputs.result}}"
        VLOGGER_RESULTS: "${{steps.vlogger.outputs.result}}"
        PAINTING_RESULTS: "${{steps.painting.outputs.result}}"
        USERAPP_RESULTS: "${{steps.userapp.outputs.result}}"
      with:
        runners: player,vlogger,painting,userapp
