name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test complete
      id: test-complete
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test complete
        setup-command: gradle build
        command: gradle test
        timeout: 10
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-COMPLETE_RESULTS: "${{steps.test-complete.outputs.result}}"
      with:
        runners: test-complete
